django_demo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('student/', include('student.urls'))
]

student/urls.py
from django.urls import path
from . import views

app_name = 'student'
urlpatterns = [
    path('', views.index, name='StudentList'),
    path('<int:student_id>/', views.student_detail, name='StudentDetail'),
    path('<int:student_id>/edit', views.edit_student, name='EditStudent'),
    path('<int:student_id>/delete', views.delete_student, name='DeleteStudent'),
    path('student/new', views.add_student, name='AddStudent')
]

student/models.py
from django.db import models


# Create your models here.
class Student(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    age = models.IntegerField()

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

student/views.py
from django.shortcuts import render
from student.models import Student
from student.form.StudentForm import StudentForm
from django.http import HttpResponseRedirect


# Create your views here.
def index(request):
    students = Student.objects.all()
    context = {'student_list': students}
    return render(request, 'student_list.html', context)


def student_detail(request, student_id):
    try:
        student = Student.objects.get(pk=student_id)
    except Student.DoesNotExist:
        return render(request, 'not_found.html')

    context = {'student': student}
    return render(request, 'student_detail.html', context)


def edit_student(request, student_id):
    try:
        student = Student.objects.get(pk=student_id)
    except Student.DoesNotExist:
        return render(request, 'not_found.html')

    if request.method == 'GET':
        form = StudentForm(
            initial={'first_name': student.first_name, 'last_name': student.last_name, 'age': student.age})

    elif request.method == 'POST':
        form = StudentForm(request.POST)

        if form.is_valid():
            student.first_name = form.cleaned_data['first_name']
            student.last_name = form.cleaned_data['last_name']
            student.age = form.cleaned_data['age']

            student.save()

            return HttpResponseRedirect('/student/')

    context = {'student': student, 'form': form}

    return render(request, 'edit_student.html', context)


def delete_student(request, student_id):
    try:
        student = Student.objects.get(pk=student_id)
    except Student.DoesNotExist:
        return render(request, 'not_found.html')

    student.delete()

    return HttpResponseRedirect('/student/')


def add_student(request):
    if request.method == 'GET':
        form = StudentForm()

    elif request.method == 'POST':
        form = StudentForm(request.POST)

        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            age = form.cleaned_data['age']

            new_student = Student(first_name=first_name, last_name=last_name, age = age)
            new_student.save()

            return HttpResponseRedirect('/student/')

    context = {'form': form}

    return render(request, 'add_student.html', context)

student/templates/add_student.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add student</title>
    <style>
        #header {
            background-color: aquamarine;
            height: 50px;
            margin: 10px;
            display: flex;
            justify-content: center;
            align-items: center;
            font-size: 30px;
        }

        #form-container {
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
            transition: 0.3s;
            padding: 50px;
            margin-right: 50px;
            width: 80%;
            display: flex;
            justify-content: center;
        }

        #container {
            display: flex;
            justify-content: center;
        }

        input {
            height: 20px;
        }

        .form-label {
            font-size: 20px;
        }

        .field-wrapper {
            margin-bottom: 10px;
        }

        #submit-button {
            padding: 10px;
            background-color: aquamarine;
            border-radius: 10px;
            width: 150px;
            text-align: center;
            font-size: 18px;
            height: 40px;
        }
    </style>
</head>
<body>
<div id="header">
    <h3>Add student</h3>
</div>

<div id="container">
    <div id="form-container">
        <form action="{% url 'student:AddStudent' %}" method="post">
            {% csrf_token %}
            <div class="field-wrapper">
                <label for="{{ form.first_name.id_for_label }}" class="form-label">First name:</label>
                {{ form.first_name }}
            </div>

            <div class="field-wrapper">
                <label for="{{ form.last_name.id_for_label }}" class="form-label">Last name:</label>
                {{ form.last_name }}
            </div>

            <div class="field-wrapper">
                <label for="{{ form.age.id_for_label }}" class="form-label">Age:</label>
                {{ form.age }}
            </div>
            <input type="submit" value="Add student" id="submit-button">
        </form>
    </div>
</div>
</body>
</html>

student/templates/delete_student.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete student</title>
</head>
<body>
    <h1>Delete student</h1>
</body>
</html>

student/templates/edit_student.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit student</title>
    <style>
        #header {
            background-color: aquamarine;
            height: 50px;
            margin: 10px;
            display: flex;
            justify-content: center;
            align-items: center;
            font-size: 30px;
        }

        #form-container {
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
            transition: 0.3s;
            padding: 50px;
            margin-right: 50px;
            width: 80%;
            display: flex;
            justify-content: center;
        }

        #container {
            display: flex;
            justify-content: center;
        }

        input {
            height: 20px;
        }

        .form-label {
            font-size: 20px;
        }

        .field-wrapper {
            margin-bottom: 10px;
        }

        #submit-button {
            padding: 10px;
            background-color: aquamarine;
            border-radius: 10px;
            width: 150px;
            text-align: center;
            font-size: 18px;
            height: 40px;
        }
    </style>
</head>
<body>

<div id="header">
    <h3>Edit student</h3>
</div>

<div id="container">
    <div id="form-container">
        <form action="{% url 'student:EditStudent' student.id %}" method="post">
            {% csrf_token %}
            <div class="field-wrapper">
                <label for="{{ form.first_name.id_for_label }}" class="form-label">First name:</label>
                {{ form.first_name }}
            </div>

            <div class="field-wrapper">
                <label for="{{ form.last_name.id_for_label }}" class="form-label">Last name:</label>
                {{ form.last_name }}
            </div>

            <div class="field-wrapper">
                <label for="{{ form.age.id_for_label }}" class="form-label">Age:</label>
                {{ form.age }}
            </div>
            <input type="submit" value="Update student" id="submit-button">
        </form>
    </div>
</div>
</body>
</html>

student/templates/not_found.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Not found</title>
</head>
<body>
    <h1>Not found</h1>
</body>
</html>

student/templates/student_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Student detail</title>
    <style>
        #details-container {
            display: flex;
            justify-content: center;
        }

        #header {
            background-color: aquamarine;
            height: 50px;
            margin: 10px;
            display: flex;
            justify-content: center;
            align-items: center;
            font-size: 30px;
        }

        #card-container {
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
            transition: 0.3s;
            padding: 20px;
            margin-right: 50px;
            width: 80%;
        }

        span {
            font-weight: bold;
        }

        p {
            font-size: 20px;
        }

        a {
            margin-right: 10px;
            font-size: 20px;
            text-decoration-color: blue;
            text-decoration: none;
            padding: 10px;
            border-radius: 8px;
            width: 20px;
            color: black;
        }

        a:hover {
            text-decoration-color: blue;
            text-decoration: none;
        }

        #buttons-container {
            margin-top: 30px;
        }

        #edit-button {
            background-color: #6bff8e;
        }

        #delete-button {
            background-color: #d75a5a;
        }
    </style>
</head>
<body>

<div id="header">
    <h3>Student details</h3>
</div>

<div id="details-container">
    <div id="card-container">
        <p><span>Id:</span> {{ student.id }}</p>
        <p><span>Name:</span> {{ student.last_name }}, {{ student.first_name }}</p>
        <p><span>Age:</span> {{ student.age }}</p>

        <div id="buttons-container">
            <a href="{% url 'student:EditStudent' student.id %}" id="edit-button">Edit</a>
            <a href="{% url 'student:DeleteStudent' student.id %}" id="delete-button">Delete</a>
        </div>
    </div>
</div>

</body>
</html>

student/templates/student_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Student List</title>
    <style>
        #header {
            background-color: aquamarine;
            height: 50px;
            margin: 10px;
            display: flex;
            justify-content: center;
            align-items: center;
            font-size: 30px;
        }

        .card-container {
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
            transition: 0.3s;
            padding: 20px;
            margin-right: 50px;
        }

        .card-container:hover {
            box-shadow: 0 8px 16px 0 rgba(0, 0, 0, 0.2);
        }

        .list-item-container {
            padding: 2px 16px;
            font-size: 23px;
        }

        a {
            text-decoration-color: blue;
            text-decoration: none;
        }

        a:hover {
            text-decoration-color: blue;
            text-decoration: none;
        }

        li {
            list-style-type: none;
        }

        #button-container {
            display: flex;
            justify-content: center;
        }

        #button {
            padding: 20px;
            background-color: aquamarine;
            border-radius: 10px;
            width: 100px;
            text-align: center;
            font-size: 18px;
        }

        p {
            font-size: 20px;
            font-weight: bold;
            text-align: center;
        }
    </style>
</head>
<body>
<div id="header">
    <h3>Student list</h3>
</div>

{% if student_list %}
<ul>
    {% for student in student_list %}
    <div class="card-container">
        <div class="list-item-container">
            <li><a href="{% url 'student:StudentDetail' student.id %}">{{ student.last_name }},
                {{ student.first_name }}</a></li>
        </div>
    </div>
    {% endfor %}
</ul>
{% else %}
<p>No students :((</p>
{% endif %}
<div id="button-container">
    <a href="{% url 'student:AddStudent' %}" id="button">Add student</a>
</div>
</body>
</html>